fos_user:
  db_driver: orm
  firewall_name: main
  user_class: App\Entity\User
  from_email:
    address: "%env(FOS_USER_EMAIL_ADDRESS)%"
    sender_name: "%env(FOS_USER_SENDER_NAME)%"
  registration:
    form:
      type: App\Form\RegistrationFormType