sonata_user:
  security_acl: true
  manager_type: orm # can be orm or mongodb
  class:
    user: App\Application\Sonata\UserBundle\Entity\User
    group: App\Application\Sonata\UserBundle\Entity\Group
  admin:
    user:
      class: App\Application\Sonata\UserBundle\Admin\Model\UserAdmin

sonata_media:
  # if you don't use default namespace configuration
  class:
    media: App\Application\Sonata\MediaBundle\Entity\Media
    gallery: App\Application\Sonata\MediaBundle\Entity\Gallery
    gallery_has_media: App\Application\Sonata\MediaBundle\Entity\GalleryHasMedia
  db_driver: doctrine_orm # or doctrine_mongodb, doctrine_phpcr it is mandatory to choose one here
  default_context: default # you need to set a context
  contexts:
    default:  # the default context is mandatory
      providers:
      - sonata.media.provider.dailymotion
      - sonata.media.provider.youtube
      - sonata.media.provider.image
      - sonata.media.provider.file
      - sonata.media.provider.vimeo

      formats:
        small: { width: 100 , quality: 70}
        big:   { width: 500 , quality: 70}

  cdn:
    server:
      path: /uploads/media # http://media.sonata-project.org/

  filesystem:
    local:
      directory:  "%kernel.root_dir%/../public/uploads/media" #flex
      #directory:  "%kernel.root_dir%/../web/uploads/media" #non-flex
      create:     false