options:
  max-time: 60
pipelines:
  master:
  - step:
      name: Deploy
      caches:
      - sshpass
      script:
      - apt-get update && apt-get -qq install sshpass
      - echo "Start deploy..."
      - ls -la
      - sshpass -p $SSH_PASS ssh -o StrictHostKeyChecking=no  -p $SSH_PORT $SSH_USERNAME@$SSH_HOSTNAME 'bash -s' < script.sh
definitions:
  caches:
    sshpass: ~/.sshpass/cache