facebook_login:
  path: /connect/check-facebook

vkontakte_login:
  path: /connect/check-vkontakte

odnoklassniki_login:
  path: /connect/check-odnoklassniki

google_login:
  path: /connect/check-google

hwi_oauth_redirect:
  resource: "@HWIOAuthBundle/Resources/config/routing/redirect_41.xml"
  prefix:   /connect

hwi_oauth_connect:
  resource: "@HWIOAuthBundle/Resources/config/routing/connect_41.xml"
  prefix:   /connect

hwi_oauth_login:
  resource: "@HWIOAuthBundle/Resources/config/routing/login_41.xml"
  prefix:   /connect